all:
  vars:
    control_plane_endpoint: 192.168.1.180
    load_balancer_ip_pool:
      - 10.0.0.0/24
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.190, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.191, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1}
    workers:
      hosts:
